### ISSUE TITLE
Player inventory

### ISSUE THREAD

**Issue by V1ck3s** [SA-MP-Developer/SemiRP#1]
Make a player inventory

**Comment by Papawy** [comment]
Player inventory should be a ListDialog. I am wondering how to deal with quantity inside inventory.

**Comment by V1ck3s** [comment]
> 
> 
> Player inventory should be a ListDialog. I am wondering how to deal with quantity inside inventory.

It will use Header Tablist. For Quantity, I think we have to open a dialog so that the player can choose the quantity.

**Comment by V1ck3s** [comment]
The base has been developed.
To test and add functionality if necessary.
