### ISSUE TITLE
Cell phone will be an object ?

### ISSUE THREAD

**Issue by V1ck3s** [SA-MP-Developer/SemiRP#2]
Cell phone will be an object ?
If yes, will it be counted in the inventory ?

**Comment by Papawy** [comment]
Cell phone can be an object. To enable cell phone functionality and commands we should check  if player have it in his inventory. We can do a _generic_ function to ease the check for item in inventory.

Can a player have multiple cell phones ? If yes we need to do a system to have an _active_ cell phone or default one.

**Comment by V1ck3s** [comment]
Phone is an item.
Character can have multiple phone.
Character have a default phone.
A phone can ring even if a character doesn't have it.
